Repository yukinarit/mapbox-gl-rs, pull requests merged in 2023-04, with the labels that each got.

#28 Add an example of Leptos
  Cargo.toml
  examples/Cargo.toml
  examples/leptos-simple/.gitignore
  examples/leptos-simple/Cargo.toml
  examples/leptos-simple/README.md
  examples/leptos-simple/index.html
  examples/leptos-simple/src/main.rs
Labels: enhancement

#29 Bump version to 0.3.0
  Cargo.toml
  README.md
Labels: ignore-for-release

#31 Add example filter to release.yml
  .github/release.yml
Labels: ci
